apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: netbox
  description: Netbox Devices API
spec:
  type: openapi
  lifecycle: production
  owner: my-team
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Devices API
      license:
        name: MIT
    servers:
      - url: https://netbox-demo.netboxlabs.com/api/
    components:
      securitySchemes:
        BearerAuth:
          type: http
          scheme: bearer
    security:
      - BearerAuth: []
    paths:
      /dcim/devices/:
        get:
          summary: List all devices
