apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: netbox
  description: Netbox Devices API
spec:
  type: openapi
  lifecycle: production
  owner: my-team
  definition: https://netbox-demo.netboxlabs.com/api/schema/
