apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: Netbox
  description: TestNetBox
spec:
  targets:
    - ./apis/netbox-api.yaml
definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Devices API
      license:
        name: MIT
    servers:
      - url: https://netbox-demo.netboxlabs.com/api/
    paths:
      //dcim/devices/:
        get:
          summary: List all devices
